import type { Metadata } from "next";
import "./globals.css";
import "@fontsource/montserrat";
import "@fontsource/montserrat/400.css";
import "@fontsource/montserrat/600.css";
import "@fontsource/montserrat/500.css";
import "@fontsource/montserrat/700.css";


export const metadata: Metadata = {
  title: "Ply Health",
  description: "Generated by create next app",
  icons: {
    icon: 'https://framerusercontent.com/images/HK05sA0ydu4tXRsw4Ylna9FbEQ.svg'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-[#fafbfd] antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
